name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Configure Git user
      run: |
        git config --global user.email "1252707+amalv@users.noreply.github.com "
        git config --global user.name "amalv"

    - name: Determine release type
      id: release_type
      run: |
        commit_message=$(git log -1 --pretty=%B)
        if [[ "$commit_message" == *"release:major"* ]]; then
          echo "release_type=major" >> $GITHUB_ENV
        elif [[ "$commit_message" == *"release:minor"* ]]; then
          echo "release_type=minor" >> $GITHUB_ENV
        elif [[ "$commit_message" == *"release:patch"* ]]; then
          echo "release_type=patch" >> $GITHUB_ENV
        else
          echo "release_type=none" >> $GITHUB_ENV
        fi

    - name: Update package.json version
      if: env.release_type != 'none'
      run: |
        npm version ${{ env.release_type }} --no-git-tag-version
        git add package.json
        git commit -m "chore: bump version to $(jq -r .version package.json)"

    - name: Push changes
      if: env.release_type != 'none'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    - name: Create GitHub Release
      if: env.release_type != 'none'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=$(jq -r .version package.json)
        release_name="Release $version"
        release_body="Automated release $version"
        gh release create v$version -t "$release_name" -n "$release_body"

    - name: Upload docs
      if: env.release_type != 'none'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=$(jq -r .version package.json)
        gh release upload v$version ./docs/*.md --clobber
